---
name: Leftwich
surname: Philip
position: "Associate Professor"
address: "School of Biological Sciences, University of East Anglia, Norwich, UK"
phone: 
www: philip-leftwich.github.io
email: "p.leftwich@uea.ac.uk"
twitter: philipleftwich
github: Philip-Leftwich
linkedin: Philip Leftwich
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(tibble)
library(here)
library(readr)
```

# Some stuff about me

\textbf{something about me}


# Education

```{r}
read_csv(here("data", "modules.csv")) %>% 
  detailed_entries(what = `Level`, 
                   with = `Institute`, 
                   when = `Year`, 
                   where = `Location`,
                   why = `Modules`)
```

# Skills

```{r}
read_csv(here("data", "skills.csv")) %>% 
  detailed_entries(what = `Skills`, why = `List`)
```

# Publications

```{r}
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
